/**************************************************************************
* Project            : End-to-End Clinical SAS Programming Portfolio Project
* Author             : Mudit Kumar Srivastava 
* GitHub Repository  : Clinical-SAS-Programming-CDISC-SDTM-ADaM-TLF-Projects

* Program Name       : T_Macros_Age_Safety_ITT.sas
* Program Purpose    : Creation of Table for Safety and ITT population using Macros - Age Statistics
* Population         : Safety and ITT population
* Output             : OUTPUT_Table_14_1_3.RTF and OUTPUT_Table_14_1_4.RTF
* Source Dataset     : ADSL
*
* SAS Version        : SAS 9.4
* Operating System   : Windows 11
*
* Input Variables    : AGE TRT01A SAFFL ITT
* Key Procedures                 
                     - PROC SQL
                     - PROC FREQ
                     - PROC MEANS
*                    - PROC REPORT
*                    - PROC TRANSPOSE
                     - PROC SQL MACROS
                     - MACRO AND MEND 

* Validation Method  : Independent QC Program Method : PROC COMPARE
* Traceability       : Raw Data --> SDTM DM --> ADAM ADSL --> TABLE

* Programming Notes  :
*   - Summary statistics generated by treatment group.
*   - Includes N, Mean, SD, Median, Min and Max.
*   - Safety population defined as SAFFL='Y' and ITT population defined as ITTFL='Y'
*   - Output formatted according to TLF standards.

**************************************************************************/

LIBNAME ADAM "Path\ADaM";

/*BIG N COUNT DERIVATION FOR SAFFL POPULATION*/
/*PROGRAM WITH MACROS*/
DATA ADSL_POP;
SET ADAM.ADSL;
IF TRT01A NE " " AND SAFFL = "Y";
OUTPUT;
TRT01A="ALL";
TRT01AN=3;
OUTPUT;
KEEP USUBJID TRT01A TRT01AN SAFFL AGE;
RUN;

/*COUNT FOR TRT A AND TRT B ALONG WITH TRT ALL*/
PROC FREQ DATA=ADSL_POP;
TABLE TRT01AN/ OUT=CHK (DROP=PERCENT);
RUN;

/*PROC SQL INTO CLAUSE MACRO TO STORE VALUE IN GLOBAL MACRO*/
PROC SQL;
SELECT COUNT
INTO :N1-:N3
FROM CHK;
QUIT;

%PUT &N1 &N2 &N3;


/*TO AGE STATS FOR SAFFL & ITT POPULATION OR ANY OTHER*/

/*SAME PROGRAM WITH MACROTISED METHOD FOR SAFFL & ITT POPULATION*/;

%MACRO STS_AGE(V1=,V2=,V3=);

DATA ADSL;
SET ADAM.ADSL;
IF TRT01A NE " " AND &V1 = "Y";
OUTPUT;
TRT01A="ALL";
TRT01AN=3;
OUTPUT;
KEEP USUBJID TRT01A TRT01AN &V1 AGE;
RUN;

PROC FREQ DATA=ADSL;
TABLE TRT01AN/ OUT=CHK (DROP=PERCENT);
RUN;

PROC SQL;
SELECT COUNT
INTO :N1-:N3
FROM CHK;
QUIT;

%PUT &N1 &N2 &N3;

/*STEP 2- AGE STATISTICS OF (Safety Population) */

PROC MEANS DATA=ADSL NWAY ; 
CLASS TRT01AN TRT01A;
VAR AGE;
/*STORING STATISTICS VALUES IN NEW VARIABLES*/
OUTPUT OUT= AGE_STS N=_N MEAN=_MEAN STD=_SD MEDIAN=_MEDIAN MIN=_MIN MAX=_MAX ;
RUN;

/*CONTROLLING DECIMALS AS PER MOCK OF STATISTICS VALUES */

DATA STS (DROP=_TYPE_ _FREQ_ _N _MEAN _SD _MEDIAN _MIN _MAX) ;
SET AGE_STS;
N=LEFT(PUT(_N,3.));
Mean=LEFT(PUT(_MEAN,4.1));
SD=LEFT(PUT(_SD,5.2));
Median=LEFT(PUT(_MEDIAN,4.1));
Minimum=LEFT(PUT(_MIN,3.));
Maximum=LEFT(PUT(_MAX,3.));
RUN;

/*COLOUMN VALUES INTO ROWS*/
PROC TRANSPOSE DATA=STS OUT=STS2 PREFIX=T;
ID TRT01AN;
VAR N MEAN SD MEDIAN MINIMUM MAXIMUM;
RUN;
/* ADDING Age (Years) LABLES AS PER MOCK */
DATA DUMMY;
_NAME_= "Age (Years)";
RUN;
/*APPENDING TWO DATASETS*/
DATA STS3;
SET DUMMY STS2;
RUN;

/* DISPLAY STATISTICS OF (Safety Population) IN RTF THROUGH PROC REPORT*/
TITLE1 J=L "Protocol: 043-1810"; 
TITLE2 J=C "Table 14.1.3  Subject Demographics - Age (&V2)";
FOOTNOTE1 J=L "Safety Population";
ODS RTF FILE="Path\&V3..RTF" STYLE=STYLES.TEST;

OPTION ORIENTATION=LANDSCAPE;
ODS ESCAPECHAR="^";

PROC REPORT DATA=STS3 SPLIT="|";
COLUMN _NAME_ T1 T2 T3;

DEFINE _NAME_ / "CATEGORY"  
STYLE (HEADER)={JUST= L CELLWIDTH=30%}
STYLE (COLUMN)={JUST= L CELLWIDTH=30%};

DEFINE T1 / "DRUG A | (N=&N1)"  
STYLE (HEADER)={JUST= L CELLWIDTH=15%}
STYLE (COLUMN)={JUST= L CELLWIDTH=15%};

DEFINE T2 / "DRUG B | (N=&N2)"   
STYLE (HEADER)={JUST= L CELLWIDTH=15%}
STYLE (COLUMN)={JUST= L CELLWIDTH=15%};

DEFINE T3 / "ALL | (N=&N3)"  
STYLE (HEADER)={JUST= L CELLWIDTH=15%}
STYLE (COLUMN)={JUST= L CELLWIDTH=15%};

COMPUTE BEFORE _PAGE_;
LINE@1  "^{STYLE[BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1  "^{STYLE[BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

RUN;

TITLE;
ODS RTF CLOSE;

%MEND;


/*CALLING THE MACROS FOR SAFFL*/
%STS_AGE (V1=SAFFL,
      V2=%STR (Safety Population),
	  V3= %STR (OUTPUT_Table_14_1_3)
	  );

/*CALLING THE MACROS FOR ITTFL*/
%STS_AGE (V1=ITTFL,
      V2=%STR (ITT Population),
	  V3= %STR (OUTPUT_Table_14_1_4)
	  );


